editorjs/urls.py
from django.urls import path

from .import views

app_name = 'editorjs'
urlpatterns = [
    path('', views.index, name='index'),
    path('editor', views.editor, name='editor'),
    path('<uuid:note_id>', views.view_note, name='view_note'),
    path('api/update', views.update_note, name='update_note'),
    path('api/fetch', views.fetch_note, name='fetch_note'),
]

tiny/urls.py
from django.urls import path

from . import views

app_name = 'tiny-notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('editor', views.editor, name='editor'),
    path('<uuid:note_id>', views.view_note, name='note'),
    path('api/save-note', views.save_note, name='save-note'),
    path('api/load-note', views.load_note, name='load-note'),
]

william/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('quill-notes/', include('quill.urls', namespace='quill-notes')),
    path('editorjs-notes/', include('editorjs.urls', namespace='editorjs-notes')),
    path('tiny-notes/', include('tiny.urls', namespace='tiny-notes')),
]

editorjs/models.py
from uuid import uuid4
from django.db import models


class EditorNote(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=500, default='')
    raw_data = models.TextField(default='')
    note_id = models.UUIDField(default=uuid4())

editorjs/views.py
from uuid import uuid4
from django.shortcuts import render
from django.http import JsonResponse

from rest_framework.decorators import api_view

from quill.utils import make_response

from .models import EditorNote

def index(request):
    notes = EditorNote.objects.all()
    context = {'all': notes}
    return render(request, 'editorjs/index.html', context)

def editor(request):
    note_id = request.GET.get('note_id', '')
    try:
        note = EditorNote.objects.get(note_id=note_id)
    except:
        note = None
    return render(request, 'editorjs/editor.html', {'note': note})

def view_note(request, note_id):
    try:
        note = EditorNote.objects.get(note_id=note_id)
    except:
        note = None
    return render(request, 'editorjs/note.html', {"note": note})

@api_view(["POST"])
def update_note(request):
    data = request.POST
    try:
        note_id = data.get('note_id')
        note = EditorNote.objects.get(note_id=note_id)
        note.title = data.get('title')
        note.raw_data = data.get('raw_data')
        note.save()
        response = make_response(True, 'Update note', {'note_id': note.note_id})
        return JsonResponse(response)
    except:
        note = EditorNote.objects.create(
            title=data.get('title'),
            raw_data=data.get('raw_data'),
            note_id=uuid4()
        )
        note.save()
        response = make_response(True, 'Saved note', {'note_id': note.note_id})
        return JsonResponse(response)

@api_view(['GET'])
def fetch_note(request):
    note_id = request.GET.get('note_id', '')
    try:
        note = EditorNote.objects.get(note_id=note_id)
        data = {
            "title": note.title,
            "raw_data": note.raw_data,
            "note_id": note.note_id
        }
        response = make_response(True, "Fetched", data)
        return JsonResponse(response)
    except:
        response = make_response(False, "Failed to fetch", errors=[{"message": "Failed to fetch"}])
        return JsonResponse(response)

editorjs/templates/editorjs/editor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit notes here..</title>
</head>
<body>
    <h3>Editor</h3>
    <button id="save">Save</button>
    <span id="feedback"></span>
    <hr>

    <input type="hidden" name="note-id" id="note-id" value="{{note.note_id}}">
    
    Title: <input type="text" id="title">
    <div id="editor" style="border:3px solid"></div>
    
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    
    {% load static %}
    <script src="{% static 'editorjs/custom/scripts/app.js' %}"></script>
</body>
</html>

editorjs/templates/editorjs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editor JS</title>

</head>
<body>
    {% if all %}
    <a href="{% url 'editorjs-notes:editor' %}">Create more</a>
    {% for note in all %}
    <h3><a href="{% url 'editorjs-notes:view_note' note.note_id %}">{{ note.title }}</a></h3>
    {% endfor %}
    {% else %}
    No notes here. <a href="{% url 'editorjs-notes:editor' %}">Create one</a>
    {% endif %}
    
</body>
</html>

editorjs/templates/editorjs/note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note!</title>

</head>
<body>
    <input type="hidden" name="note-id" id="note-id" value="{{note.note_id}}">
    <a href="{% url 'editorjs-notes:editor' %}?note_id={{note.note_id}}">Edit</a>
    <h3 id="title"></h3>
    <div id="display"></div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>

        let convertDataToHtml = (blocks) => {
            var convertedHtml = "";
            blocks.map(block => {
            
            switch (block.type) {
                case "header":
                convertedHtml += `<h${block.data.level}>${block.data.text}</h${block.data.level}>`;
                break;
                case "embded":
                convertedHtml += `<div><iframe width="560" height="315" src="${block.data.embed}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>`;
                break;
                case "paragraph":
                convertedHtml += `<p>${block.data.text}</p>`;
                break;
                case "delimiter":
                convertedHtml += "<hr />";
                break;
                case "image":
                convertedHtml += `<img class="img-fluid" src="${block.data.file.url}" title="${block.data.caption}" /><br /><em>${block.data.caption}</em>`;
                break;
                case "list":
                    let openTag = "";
                    let closeTag = "";

                    if (block.data.style === "unordered"){
                        openTag = "<ul>";
                        closeTag = "</ul>";
                    }
                    else if (block.data.style === "ordered") {
                        openTag = "<ol>";
                        closeTag = "</ol>";
                    }
                convertedHtml += openTag;
                block.data.items.forEach(function(li) {
                    convertedHtml += `<li>${li}</li>`;
                });
                convertedHtml += closeTag;
                break;
                default:
                console.log("Unknown block type", block.type);
                break;
            }
            });
            return convertedHtml;
        }

        let display = (noteId) => {
            $.ajax({
                "url": "/editorjs-notes/api/fetch",
                "method": "GET",
                "data": {"note_id": noteId},
                "success": (resp) => {
                    if (resp.success) {
                        let html = convertDataToHtml(JSON.parse(resp.data.raw_data).blocks)
                        $("#display").html(html)
                        $("#title").text(resp.data.title)
                    }
                }
            })
        }
        display($("#note-id").val())
    </script>
</body>
</html>