tiny/urls.py
from django.urls import path

from . import views

app_name = 'tiny-notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('editor', views.editor, name='editor'),
    path('<uuid:note_id>', views.view_note, name='note'),
    path('api/save-note', views.save_note, name='save-note'),
    path('api/load-note', views.load_note, name='load-note'),
]

william/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('quill-notes/', include('quill.urls', namespace='quill-notes')),
    path('editorjs-notes/', include('editorjs.urls', namespace='editorjs-notes')),
    path('tiny-notes/', include('tiny.urls', namespace='tiny-notes')),
]

tiny/models.py
from uuid import uuid4

from django.db import models

class TinyNote(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    public_id = models.UUIDField(default=uuid4())
    content = models.TextField(default="")

tiny/views.py
from uuid import uuid4

from django.http import request
from django.shortcuts import render
from django.http import JsonResponse

from rest_framework.decorators import api_view

from .models import TinyNote


def make_response(
    success: bool,
    message: str,
    data: dict = None,
    errors: list = None):

    if success:
        if not data:
            raise Exception("Successful response must have a payload")
        return {
            'success': True,
            'message': message,
            'data': data
        }
    if not success:
        if not errors:
            raise Exception("Failed response must have a list of errors")
        return {
            'success': False,
            'message': message,
            'errors': errors
        }


def index(request):
    all = TinyNote.objects.all()
    return render(request, 'tiny-notes/index.html', {'all': all})

def editor(request):
    note_id = request.GET.get('note-id', 'new-note')
    # content from existing notes are not properly loaded into tinymce editor
    # we'd have to wait for editor to finish loading. don't wanna do it, i'm bored
    # and won't be picking tinymce anyways..
    return render(request, 'tiny-notes/editor.html', {"note_id": note_id})

def view_note(request, note_id):
    return render(request, 'tiny-notes/note.html', {'note_id': note_id})

@api_view(['POST'])
def get_note(request):
    pass

@api_view(['POST'])
def save_note(request):
    try:
        note_id = request.POST['note-id']
        if note_id == "new-note":
            note = TinyNote.objects.create(
                title=request.POST['title'],
                content=request.POST['content'],
                public_id=uuid4()
            )
            note.save()
            resp = make_response(
                success=True,
                message='Saved successfully',
                data={"note_id": note.public_id}
            )
            return JsonResponse(resp)
        print(">>>", note_id)
        note = TinyNote.objects.get(public_id=note_id)
        note.title = request.POST['title']
        note.content = request.POST['content']
        note.save()
        resp = make_response(
            success=True,
            message='Updated successfully',
            data={"note_id": note.public_id}
        )
        return JsonResponse(resp)
    except:
        raise
        resp = make_response(
            success=False,
            message='Some error has occurred',
            errors=[{"message": "Some error has occurred"}]
        )
        return JsonResponse(resp)

@api_view(['POST'])
def load_note(request):
    try:
        note_id = request.POST['note-id']
        note = TinyNote.objects.get(public_id=note_id)
        resp = make_response(True, 'Note loaded successfully', {
            "note_id": note.public_id,
            "title": note.title,
            "content": note.content
        })
        return JsonResponse(resp)
    except:
        resp = make_response(
            success=False, 
            message='Some error has occured', 
            errors=[{"message": "Some error has occured"}]
            )
        return JsonResponse(resp)

tiny/templates/tiny-notes/editor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tiny Editor</title>

</head>
<body>
    <!DOCTYPE html>
<html>
<head>
    
    <form id="tiny-form">
        <input type="hidden" name="note-id" id="note-id" value="{{ note_id }}">
        <input type="text" name="note-title" id="title">
        <textarea id="tiny-textarea"></textarea>
        <button id="save-btn">Save</button><small id="feedback"></small>
    </form>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        tinymce.init({ selector:"textarea" });
        $("#save-btn").click((e) => {
            e.preventDefault();
            let title = $("#title").val();
            let content = tinyMCE.activeEditor.getContent();
            let noteId = $("#note-id").val()
            $.ajax({
                method: "POST",
                url: "/tiny-notes/api/save-note",
                data: {
                    "note-id": noteId,
                    "title": title,
                    "content": content
                },
                success: (resp, status) => {
                    if (resp.success) {
                        $("#note-id").val(resp.data.note_id);
                        $("#feedback").text(resp.message);
                    }
                    else {
                        $("#feedback").text(resp.message)
                    }
                }
            })
        })

        if ($("#note-id").val() != "new-note") {
            $.ajax({
                "url": "{% url 'tiny-notes:load-note' %}",
                "method": "POST",
                "data": {
                    "note-id": $("#note-id").val()
                },
                "success": (resp) => {
                    if (resp.success) {
                        console.log(resp)
                        $("#title").val(resp.data.title);
                        tinyMCE.init({
                            oninit: () => {
                                tinyMCE.activeEditor.setContent(resp.data.content)
                            }
                        })
                    }
                    else {
                        $("#feedback").text(resp.errors[0].message)
                    }
                }
            })
        }
    </script>
</body>
</html>

tiny/templates/tiny-notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tiny Notes</title>
</head>
<body>
    <h3>All Tiny Notes</h3>
    <small>If they exist</small>

    {% if all %}
    <h5><a href="{% url 'tiny-notes:editor' %}">Create more</a></h5>
        <ul>
            {% for note in all %}
                <li><a href="{% url 'tiny-notes:note' note.public_id %}">{{ note.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h4>No Tiny notes have been created..</h4>
        <a href="{% url 'tiny-notes:editor' %}">Create one..</a>
    {% endif %}
</body>
</html>

tiny/templates/tiny-notes/note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A Tiny Note</title>
</head>
<body>
    <input type="hidden" name="note-id" id="note-id" value="{{ note_id }}">
    <a href="{% url 'tiny-notes:editor' %}?note-id={{ note_id }}">Edit note</a>
    <h3 id="note-title"></h3>
    <div id="content">

    </div>
    <div id="feedback"></div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        let noteId = $('#note-id').val()
        $.ajax({
            "url": "{% url 'tiny-notes:load-note' %}",
            "method": "POST",
            "data": {"note-id": noteId},
            "success": (resp) => {
                console.log(typeof resp, resp)
                if (resp.success) {
                    $("#note-title").text(resp.data.title)
                    $("#content").html(resp.data.content)
                }
                else {
                    $("#feedback").text(resp.errors[0].message)
                }
            }
        })
    </script>
</body>
</html>