tiny/urls.py
from django.urls import path

from . import views

app_name = 'tiny-notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('editor', views.editor, name='editor'),
    path('<uuid:note_id>', views.view_note, name='note'),
    path('api/save-note', views.save_note, name='save-note'),
    path('api/load-note', views.load_note, name='load-note'),
]

william/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('quill-notes/', include('quill.urls', namespace='quill-notes')),
    path('editorjs-notes/', include('editorjs.urls', namespace='editorjs-notes')),
    path('tiny-notes/', include('tiny.urls', namespace='tiny-notes')),
]

william/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.conf import settings

from markdown import markdown

def index(request):
    readme = settings.BASE_DIR.joinpath('README.md').read_text()
    html = markdown(readme, extensions=['markdown.extensions.tables'])
    return HttpResponse(html)

william/templates/william/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>We figure out some designs later. For now, find navigation below..</h3>
    <ol>
        <li>
            <a href="{% url 'quill-notes:index' %}">QuillJS Notes</a>
        </li>
        <li>
            <a href="{% url 'editorjs-notes:index' %}">Editor.js</a>
        </li>
        <li>
            <a href="{% url 'tiny-notes:index' %}">TinyMCE</a>
        </li>
    </ol>
</body>
</html>