quill/urls.py
from django.urls import path

from . import views

app_name='quill-notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('editor', views.editor, name='editor'),
    path('<uuid:note_id>', views.view_note, name='view_note'),
    path('api/update', views.update_note, name='update_note'),
    path('api/fetch', views.fetch_note, name='fetch_note'),
]

tiny/urls.py
from django.urls import path

from . import views

app_name = 'tiny-notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('editor', views.editor, name='editor'),
    path('<uuid:note_id>', views.view_note, name='note'),
    path('api/save-note', views.save_note, name='save-note'),
    path('api/load-note', views.load_note, name='load-note'),
]

william/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('quill-notes/', include('quill.urls', namespace='quill-notes')),
    path('editorjs-notes/', include('editorjs.urls', namespace='editorjs-notes')),
    path('tiny-notes/', include('tiny.urls', namespace='tiny-notes')),
]

quill/models.py
from django.db import models

class QuillNote(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.EmailField(default='admin@quill-notes.com')
    title = models.CharField(max_length=500)
    quill_delta = models.TextField(default='', blank=True)
    raw_text = models.TextField(default='', blank=True)
    note_id = models.UUIDField(blank=False)

quill/views.py
from uuid import uuid4

from django.core import exceptions
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from rest_framework.decorators import api_view

from .models import QuillNote
from .utils import make_response

def index(request):
    if request.method == 'GET':
        return render(
            request,
            'quill/index.html',
            {'all': QuillNote.objects.all()}
        )

def editor(request):
    if request.method == 'GET':
        note_id = request.GET.get('note_id', "")
        try:
            QuillNote.objects.get(note_id=note_id)
            valid_note = True
        except:
            valid_note = False
        context = {
            'note_id': note_id,
            'valid_note': valid_note
        }
        return render(request, 'quill/editor.html', context)

def view_note(request, note_id):
    if request.method == 'GET':
        try:
            note = QuillNote.objects.get(note_id=note_id)
            return render(request, 'quill/note.html', context={'note': note})
        except:
            # raise
            return HttpResponse('Invalid Note ID')

@api_view(['POST'])
def update_note(request):
    payload = request.POST
    try:
        note = QuillNote.objects.get(note_id=payload.get('note_id'))
        note.title = payload.get('title')
        note.quill_delta = payload.get('quill_delta')
        note.raw_text = payload.get('raw_text')
        note.save()
        response = make_response(True, 'Updated note', {'note_id': note.note_id})
        return JsonResponse(response)
    except exceptions.ValidationError:
        note = QuillNote.objects.create(
            title=payload.get('title'),
            quill_delta=payload.get('quill_delta'),
            raw_text=payload.get('raw_text'),
            note_id=uuid4()
        )
        note.save()
        response = make_response(True, 'Saved note', {'note_id': note.note_id})
        return JsonResponse(response)
    except:
        raise

@api_view(['GET'])
def fetch_note(request):
    try:
        note_id = request.GET.get('note_id')
        note = QuillNote.objects.get(note_id=note_id)
        data = {
            'title': note.title,
            'quill_delta': note.quill_delta,
            'raw_text': note.raw_text,
            'note_id': note.note_id
        }
        response = make_response(True, 'Here is your note', data)
        return JsonResponse(response)
    except:
        raise

quill/templates/quill/editor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create new Quill Note</title>

    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

</head>
<body>
    <form action="">
        <h3>QuillNote Editor</h3>

        <input type="hidden" id="note-id" name="note-id" value="{{ note_id }}">
        {% if valid_note %} <input type="hidden" name="valid" value="true" id="valid"> {% endif %}

        Title: <input id="note-title" type="text" value=""> <br>
        <div id="editor"></div>
        <input id="save-btn" type="button" value="Save">
        <span id="feedback"></span>
    </form>

    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    
    {% load static %}
    <script src="{% static 'quill/custom/scripts/app.js' %}"></script>
</body>
</html>

quill/templates/quill/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Quill Notes</title>
</head>
<body>
    <h1>Quill Notes</h1>
    {% if not all %}
        <p>There are no quill notes at this time.</p>
        <a href="{% url 'quill-notes:editor' %}">Create one..</a>
    {% else %}
        <p>List of notes..</p>
        <a href="{% url 'quill-notes:editor' %}">Create more</a>
        {% for note in all %}
            <h3><a href="{% url 'quill-notes:view_note' note.note_id %}">{{ note.title }}</a></h3>
        {% endfor %}
    {% endif %}
</body>
</html>

quill/templates/quill/note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note: {{ note.title }}</title>

    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

</head>
<body>
    <a href="{% url 'quill-notes:editor' %}?note_id={{ note.note_id }}">Edit</a><br>

    <input type="hidden" id="note-id" name="note-id" value="{{ note.note_id }}">

    <h3 id="note-title"></h3><hr>
    <div id="display"></div>


     <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
     <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $.ajax({
            method: 'GET',
            url: '/quill-notes/api/fetch',
            data: {note_id: $('#note-id').val()},
            success: function(resp, status){
                $('#note-title').text(resp.data.title)
                $('#display').html(resp.data.raw_text)
            }
        })
    </script>
</body>
</html>